version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/code/codedeploy-3
hooks:
  BeforeInstall:
    - location: aws/stop_server.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: aws/start_server.sh
      timeout: 120
